# Generated by Django 5.2.5 on 2025-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcancellation',
            name='cancelled_by',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], max_length=20),
        ),
    ]
